### ISSUE TITLE
Change how the price is set

### ISSUE THREAD

**Issue by MineTheCube** [Dasfaust/GlobalMarket#100]
Hi,

After testing your plugin, I think it's quite weird to set the price of an item. I don't think it's easy as we must try to add random 1-9 numbers, then reduce, then add..

I wonder why you didn't use the sign as you did before, I mean open a sign and we just have to put the price then click OK.

So it would be really great to add the possibility to use sign instead of typing 1-9 in the config !

**Comment by Dasfaust** [comment]
I think I'll be redoing the menu to have click-able buttons to add and subtract increments in 1-10. There's always the command in the meantime!

**Comment by MineTheCube** [comment]
Well if I want to set, let's say 643$, I have to click on +100 6 times, then +10 4 times, then +1 3 times, and maybe if I misclick, I've to reduce the price, etc...
Also, how will you handle big numbers ? If someone want to set 680,000,005 ?

Because with a sign, I type directly what I want, up to 100,000,000,000,000, I don't think it can be easier.. ;)

**Comment by malonehedges** [comment]
Quick note: Signs are limited in length, you wouldn't be able to use a number that big most likely. Anvils, however, can have much longer strings of characters.

**Comment by MineTheCube** [comment]
Actually with a sign you can write very big numbers. The maximum is 999,999,999,999,999, which is 1e+15.
