### ISSUE TITLE
Command to open players stock

### ISSUE THREAD

**Issue by Bodyash** [Dasfaust/GlobalMarket#101]
for example /market stock NickName

**Comment by Slind14** [comment]
isn't this implemented already? 
https://github.com/Dasfaust/GlobalMarket/commit/63f4a5f877e4612d35a92341223a363d5bdc79e1

**Comment by Bodyash** [comment]
Not working at all. Trying /market browse NickName - and nothing. Just opens market listings.

**Comment by Slind14** [comment]
try `/market browse stock <player>`

**Comment by Dasfaust** [comment]
That is a separate feature to open the GUI for a player.

**Comment by Slind14** [comment]
ahh, so its `/sudo /market browse stock` with essentials
