### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by Alibabaand40voleur** [Dasfaust/GlobalMarket#103]
Player can't use /market create & /market createinf.
He have this permission : 
    - globalmarket.use
    - globalmarket.command.createserverlisting

Thx for helping.

Im using : GlobalMarket-2.0.0.28.jar

**Comment by Dasfaust** [comment]
Are you using a permissions plugin? globalmarket.command.createserverlisting was changed to globalmarket.command.createinf recently.

**Comment by Alibabaand40voleur** [comment]
Now, he have that : 
    - globalmarket.use
    - globalmarket.command.createinf
And can't /market create

I use GroupManager.

**Comment by Alibabaand40voleur** [comment]
Soo... 2 Weeks, can u say me why ?

**Comment by Alflamme** [comment]
Hey i have a problem for the Permission 
what this permission of this Plugin please ?
