### ISSUE TITLE
Change language to FR

### ISSUE THREAD

**Issue by TheYaya77** [Dasfaust/GlobalMarket#105]
Hello, can you tell me how to set the language to french ? Thanks I tried fr_EU to replace en_US but it didn't work.

**Comment by Dasfaust** [comment]
It doesn't yet have a French translation. Only US English and German. I would need a contributor to get a translation done.

**Comment by Alibabaand40voleur** [comment]
If u need french traductor, i can help u !

**Comment by Lemrigue** [comment]
Hello, I can help too for french translating since I already translated the file in the .jar

**Comment by Galaxias** [comment]
#125 --> made it. :) Let me know if you find typos.
