### ISSUE TITLE
I can't add a custom item to blacklist

### ISSUE THREAD

**Issue by zzvenuszz** [Dasfaust/GlobalMarket#112]
I have essentials kit with an item like this:
    - 310:0 1 protection_environmental:3 durability:1 name:§6Mũ_Member lore:§6§l[Không_thể_giao_dịch]

I put this lore to blacklist like this but player still can sell it on market:

blacklist:
  item_name:
- Transaction Log
- Market History
  item_id:
    '0': 0
  enchant_id: []
  enchant_lore:
- '[Không thể giao dịch]'
  use_with_mail: false

I had tried this too

blacklist:
  item_name:
- Transaction Log
- Market History
  item_id:
    '0': 0
  enchant_id: []
  enchant_lore:
- '[Không_thể_giao_dịch]'
  use_with_mail: false

and this too

blacklist:
  item_name:
- Transaction Log
- Market History
  item_id:
    '0': 0
  enchant_id: []
  enchant_lore:
- '§6§l[Không_thể_giao_dịch]'
  use_with_mail: false

but it not work. 
can you add a command to add item in hand to blacklist?

**Comment by malonehedges** [comment]
Can you please put your config into code blocks? See https://guides.github.com/features/mastering-markdown/ on Syntax Highlighting.
