### ISSUE TITLE
SubCommand handling is broken.

### ISSUE THREAD

**Issue by clienthax** [Dasfaust/GlobalMarket#115]
Seems your subcommand handler does a startsWith check
This means that if the subcommand createinf is used, it gets sent to the create subcommand with a extra arg "inf",
instead of going to the correct handler.

This is on the 2.0.x branch

**Comment by pchard** [comment]
I get this error to on latest version.
Using 1.7.10 Thermos.

**Comment by DraksterAU** [comment]
You mean http://build.survivorserver.com/job/GlobalMarket%202.0.0/33/?
