### ISSUE TITLE
The stock only can be sold once

### ISSUE THREAD

**Issue by 5igm** [Dasfaust/GlobalMarket#119]
Even I stored 320 same type item in stock, I only can sell them once. 
For example, if I want to sell every glass block at 3 $ and I have stored 320 glass blocks in stock, when one player double click my good and purchase them, my listing will disappear, although there are still 319 glass blocks in my stock.  Every time, I have to create the listing again to sell the rest of same type items.

**Comment by 5igm** [comment]
GlobalMarket 2.0.0.28 Beta

**Comment by PantACRO4life** [comment]
UP same here
