### ISSUE TITLE
*.37 inventory glitch

### ISSUE THREAD

**Issue by freakyy85** [Dasfaust/GlobalMarket#124]
Everytime I enable the Economy PLugin together with GlobalMarket, items in the inventory glitch when I press shift+rigthclick. can you please fix this?
Heres a video showing it. https://youtu.be/s_Dt9KBkk5Q
When having Economy + Vault put in the plugins folder, and also putting GlobalMarket in starts the bug. Is that possible? :)

**Comment by Dasfaust** [comment]
I think I was able to reproduce this... Just to verify, when shift+click crafting, 32*4 sticks for example, I receive a stack of 60, 64, and 4. Is that the issue? Should be two stacks of 64.

**Comment by freakyy85** [comment]
yes exactly that!

**Comment by freakyy85** [comment]
can you do something about it? :)

**Comment by freakyy85** [comment]
hello? :D

**Comment by Galaxias** [comment]
Got the same problem, really a huge problem for my server. Got any workarounds?

**Comment by Dasfaust** [comment]
Sorry for my absence, been busy with work, unfortunately. Build [38](http://build.survivorserver.com/job/GlobalMarket%202.0.0/38/) should fix, if someone wants to confirm.

**Comment by freakyy85** [comment]
for me the bug is still present but it might be caused by multiple plugins.

**Comment by freakyy85** [comment]
galaxias, maybe we should get in touch because fo the problem? i mean we both have the problem maybe we can check what plugins we have in common or something and test it out?

**Comment by Dasfaust** [comment]
@freakyy85 I suppose it's possible if another plugin is using ProtocolLib in the way that I am. I can no longer reproduce the issue with build 38. Seems like a ProtocolLib bug to me, you must pass an ItemStack to MinecraftReflection before using the NBT functions. Will cause the stacking issue unless you clone the ItemStack first.

Think I'm going to write my own reflection utilities and drop ProtcolLib in a later version for a better understanding anyways.

**Comment by freakyy85** [comment]
hm ok ... i even have the problem when just shift clicking on 34 sticks. they keep unstacking.

**Comment by freakyy85** [comment]
well, i removed protocollib but the bug still happens.

**Comment by Galaxias** [comment]
I'll try the plugin in tomorrow :) Thank you for the build  @Dasfaust.  @freakyy85 --> After removing GlobalMarket, the  bug disappeared for me, so it's definitely from this plugin for me.

**Comment by Galaxias** [comment]
I can't reproduce yet with build 38. I'll let you know if it happens again. 
Thank you all. ( @freakyy85 You should really see which of your plugins uses ProtocolLib! )

**Comment by freakyy85** [comment]
cant protocollib fix it? can you maybe ask them to fix it? tell them what the problem is etc.?

**Comment by Dasfaust** [comment]
I will have to do more testing before submitting a bug report, it's just a hunch. It may also be a bug in Spigot related to CraftItemStack, as ProtocolLib uses reflection to access that class.

**Comment by freakyy85** [comment]
ok so, if uve done more testing will u submit a bugreport to the responsible people?

**Comment by freakyy85** [comment]
ok when uve done more testing, will u report the bug and how long would that take?

**Comment by dwatsX** [comment]
although build 38 did not fix this issue for me initially, installing the new version of ProtocolLib which was released today, has fixed this for me.

**Comment by dwatsX** [comment]
apparently 1.11.2 has made this an issue again. It's not the same as before though. Items seem to properly stack in players' inventories, but they will not stack properly when shift+clicking items into chests. In most cases, players have to manually stack items in their inventories before placing the items into a chest.

**Comment by Dasfaust** [comment]
1.11.2 has been working fine for me - can't reproduce the bug. Also can't say when I'd be able to submit a proper bug report to the ProtocolLib people.
