### ISSUE TITLE
It will not install to my server

### ISSUE THREAD

**Issue by SlenderFinder** [Dasfaust/GlobalMarket#126]
I have the plugin installed but everytime I try to do /market. I get "unknown command. type "/help" for help". Can someone help me please, I really like this plugin but it will not work.

**Comment by Galaxias** [comment]
Sorry to ask that question but 
1. Have you placed GlobalMarket.jar (or whatever) in your /plugins/ folder, 
2. Have you installed Vault and ProtocolLib (the development versions) 
3. Could you provide Bukkit/Spigot logs?

**Comment by SlenderFinder** [comment]
http://pastebin.com/vR2sKuDL
I have everything installed

**Comment by Galaxias** [comment]
Ok. I'm sorry, i meant your startup logs.
