### ISSUE TITLE
Player Perms

### ISSUE THREAD

**Issue by Pluto-Picra** [Dasfaust/GlobalMarket#139]
My players do not have permission to use any perms other than /market. I have looked everywhere for the right commands to give them to use the market. can someone please help me.

**Comment by Chew** [comment]
I have this problem too.

**Comment by yonatand** [comment]
I have this problem aswell

**Comment by Dasfaust** [comment]
I am closing this issue as `wontfix`, as this repository is going to be archived. You are welcome to fork and republish the project, if you wish. I know this issue is very old, sorry for the ping!
