### ISSUE TITLE
[Feature-Request] Multi-Server Support

### ISSUE THREAD

**Issue by Slind14** [Dasfaust/GlobalMarket#14]
...

**Comment by Nentify** [comment]
Multi-server support would be very convenient.

**Comment by madtomic** [comment]
You can use the same database across all servers.

**Comment by rfox90** [comment]
Which will have synchronisation and locking issues on pretty much EVERY transaction.

**Comment by Nentify** [comment]
Yes, I have tried this and purchasing an item on one server doesn't remove it from the other. Easy issues with item duplication here.

**Comment by madtomic** [comment]
Oh yea, I forgot about this the locking issues and duplications. This locking is to prevent database from being hacked and preserve the data if shall the server crashes.

The only way to get GlobalMarket across more than one server is to lock all items in the database and have an order fill queue system to fill all orders when players are browsing and buying. It would be difficulty but not impossible.

Example:
First, break up the items into categories and have it load up based on what the player is browsing for. This would help break up the load when a lot of players are browsing and buying from the market across many servers.

The categories can be done through filtering and configurable via categories.yml file. All items are check against the filter and put in correct categories or table in a database.

Now the easy part is done the hardest part is synchronization between servers.

Example:
Player 1 in world 1 is browsing and buying for apples in Food.
Player 2 in world 1 is also browsing and buying for apples in Food.
Player 3 in world 2 is browsing and buying for carrots in Food.
Player 4 in world 3 is browsing and buying for carrots in Food.

In this example, all players would be able to buy/browse at the same time using the order fill queue system.

All orders are filled based on who buys the item first. Like how transaction log works. Each sale, generates a mail or book with transaction. This same method can be use for order placing.
An order transaction goes in, it checks by the order fill queue system and outputs the item or refund via transaction log.

The order fill queue system will need something to track orders. This is where Transaction ID (TID) comes in. It will track which order comes first and fill the order based on the available quantity on the market. If an order came in too late, it would mail the money back like the transaction log.

The check is for order time (TID), quantity and price vs. units, quantity and price on market. There can be same items but different quantity and price. All this data is in realtime and is updated when a player open, buy and browse the market.

This order fill queue system would allow everyone to browse and buy at the same time. Now the real hardest part is code this. 


  based in different windows. yway unless items are locked a player is looking at it.

Example:
Player 1 in world 1 buys the same log the same time that player 2 in world 2 is trying. The only solution is

**Comment by madtomic** [comment]
I think it will be better support in GlobalMarket 2.0!!!
https://github.com/Dasfaust/GlobalMarket/issues/26

**Comment by Nentify** [comment]
:o That sounds exciting. Currently I have a shared market server. :P

**Comment by Dasfaust** [comment]
I actually tackled this awhile ago, here it is in action: http://www.gfycat.com/ScarceGentleAllosaurus It uses Redis to sync data. It'll be in version 2 whenever that gets finished.

**Comment by Nentify** [comment]
Wow, that looks really nice, looking forward to version 2!

**Comment by madtomic** [comment]
Very nice Dasfaust! I can't wait for 2.0.

**Comment by Slind14** [comment]
@Dasfaust is there any beta version of the redis bridge available or is it still highly experimental/wip?

**Comment by Dasfaust** [comment]
Done in [version 2.0.0](https://github.com/Dasfaust/GlobalMarket/tree/2.0.X).

**Comment by rfox90** [comment]
Thanks, you're the best :D
