### ISSUE TITLE
Table Prefixes

### ISSUE THREAD

**Issue by LeviRosol** [Dasfaust/GlobalMarket#3]
Hi. First off, I'm testing your plugin for a new server we're putting together, and so far, it's awesome.

I have one request at this point. Could you add a prefix to the mysql tables that are created? Ideally it would be something you could set in the config, but at minimum, a default would be awesome.

Thanks!

**Comment by madtomic** [comment]
Can you work on this if you could. Table Prefix for GolbalMarket database. Thanks
