### ISSUE TITLE
[Feature Request] Buying Listings

### ISSUE THREAD

**Issue by damonmensch** [Dasfaust/GlobalMarket#30]
Allow players to make listings for items they wish to buy. Require them to put the money aside when listing is made.
example command: /market buy <item id> [amount] <price>

Amount can be omitted, with default at 1. Maybe also make <item id> replaceable with "this" to buy what's in the player's hand. Then have it show up in the listings but instead of saying buy say sell, and will take the item out of the player's current inventory.

**Comment by hunter688** [comment]
This feaure is really useful. Many players want add to market items they wish to buy.

**Comment by madtomic** [comment]
I like this. My players also make similar request. Maybe ways to add a way to make offers on the market?
