### ISSUE TITLE
Hopper duplicate bug - Please disable until fix.

### ISSUE THREAD

**Issue by madtomic** [Dasfaust/GlobalMarket#35]
Hopper duplicate bug still resides in 1.7.x

I know the hopper is already disabled in 1.8.x but can we also disable it in 1.7.

Thanks!

**Comment by Nentify** [comment]
Also having this issue in 1.7.10, an option to disable would be appreciated!

**Comment by Nentify** [comment]
http://nentify.me/GlobalMarket-1.3.0-6baa184.jar - Latest build with hopper removed from GUI.

**Comment by madtomic** [comment]
This build is for 1.8 or 1.7?

**Comment by Feldmarschall** [comment]
Same problem. Pls remove hopper for 1.7.x. :)
ProtocolLib is importan for other plugins.

Thanks

**Comment by Nentify** [comment]
No problem, I just commented out the hopper section of ItemListings.java and re-compiled the plugin, If you want to do it yourself you'll just need to delete that part of the code and re-compile. https://github.com/Dasfaust/GlobalMarket/blob/master/src/main/java/com/survivorserver/GlobalMarket/ListingsInterface.java#L68-111

**Comment by Dasfaust** [comment]
Try build 9: http://build.survivorserver.com/job/GlobalMarket/9/

**Comment by Nentify** [comment]
Updating to this build caused a lot of items to be transformed into Transaction Logs again, seems odd that this code change would cause this... Is there a proper update procedure or did my changes break how items are stored or something?

**Comment by Dasfaust** [comment]
Nothing but the hopper code was changed. See my [other comment](https://github.com/Dasfaust/GlobalMarket/issues/37#issuecomment-69562518).

**Comment by Nentify** [comment]
To feed back on this, I believe this is now fixed. Will reply if I re-encounter the issue.

**Comment by madtomic** [comment]
I found other bugs but they are not related to hopper. I can said in latest build it is fix.
