### ISSUE TITLE
Transaction logs being sent to the wrong people?

### ISSUE THREAD

**Issue by Nentify** [Dasfaust/GlobalMarket#36]
Some users on my server are reporting transaction logs being sent to their mailbox for items they haven't sold. Don't have any other information yet, but using the latest builds of both GlobalMarket and MarketCompanion on Cauldron with Forge 1272.

**Comment by Nentify** [comment]
Apparently users are also receiving money from the transaction as well... I really don't know what to make of it.

**Comment by madtomic** [comment]
I have to test this. I know sometimes, mailbox will have both transactions logs and items in market. Check to see if the player change the sorting in mailbox.

**Comment by Nentify** [comment]
It's not that, a user gave me his transaction log that said someone bought his diamond, but he never put a diamond up for sale. Is it possible to put the seller's name in the book title, book meta/author or the actual book itself perhaps?

**Comment by madtomic** [comment]
You do know you can make a transaction log looking like the one you get from the market.

**Comment by Nentify** [comment]
Yeah, I doubt multiple users would just lie for the sake of a transaction log though. :P

**Comment by madtomic** [comment]
HAHA, like I said. If you are using it across servers now. All types of bugs can happen!

**Comment by Nentify** [comment]
Moved convo to #37
