### ISSUE TITLE
Items in marketplace transforming into transaction logs

### ISSUE THREAD

**Issue by Nentify** [Dasfaust/GlobalMarket#37]
Users are still able to put their transaction logs up for sale, even though the item name is blacklisted in the config file.

**Comment by madtomic** [comment]
Can you post your config file here and a screenshot of the transaction book with the mouse over info

**Comment by Nentify** [comment]
http://i.nentify.me/iicKfFcu.png

However, I don't think this is the issue. I think items in the market are transforming into the transaction log (as reported by multiple users). I think this is related to this: https://github.com/Dasfaust/GlobalMarket/issues/36 as I removed all the transaction logs from the market on occasion as they were taking up a lot of space, and therefore 'transformed' transaciton logs were ending up back in user's mailboxes.

**Comment by madtomic** [comment]
May I ask this is before the hopper change or after? Are you using more than one servers with one database?

**Comment by Nentify** [comment]
I believe this was before the hopper change, and there is only one server with the plugin connecting to 1 market database.

**Comment by madtomic** [comment]
Ok, I will do some more testings as I am still unable to list anything that is blocked.

**Comment by Nentify** [comment]
Sorry - You can't list anything that's blocked. The issue (I believe), is items are 'turning into' transaction logs in the market. I'm not really sure why. I'm going to try resetting the databases.

**Comment by Nentify** [comment]
[21:29:00 WARN]: [GlobalMarket] Null IMarketItem in InventoryClickEvent with position 6 (raw: 6) in interface Listings, should have an ID of 5.
[21:29:01 WARN]: [GlobalMarket] Null IMarketItem in InventoryClickEvent with position 6 (raw: 6) in interface Listings, should have an ID of 5.
[21:29:02 WARN]: [GlobalMarket] Null IMarketItem in InventoryClickEvent with position 6 (raw: 6) in interface Listings, should have an ID of 5.
[21:29:03 WARN]: [GlobalMarket] Null IMarketItem in InventoryClickEvent with position 6 (raw: 6) in interface Listings, should have an ID of 5.
[21:29:04 WARN]: [GlobalMarket] Null IMarketItem in InventoryClickEvent with position 6 (raw: 6) in interface Listings, should have an ID of 5.
[21:29:05 WARN]: [GlobalMarket] Null IMarketItem in InventoryClickEvent with position 4 (raw: 4) in interface Listings, should have an ID of 25.

I get this in the log sometimes, not really sure what it means or if it's related to this.

**Comment by madtomic** [comment]
You will need to reset the database. That is the only suggestion now. You can just drop history, items, listings and mail

**Comment by Nentify** [comment]
I have done this for now, will see if any other issue occur now. 
On 12 Jan 2015 03:39, madtomic <notifications@github.com> wrote:You will need to reset the database. That is the only suggestion now. You can just drop history, items, listings and mail

**Comment by Dasfaust** [comment]
This is a duplicate issue of #9, but it doesn't really matter. I still don't know a cause. I've heard of success by using SQLite, or turning on queues like externo suggested in the other issue. Also with the "Null IMarketItem" messages, this issue sounds like desync from the database. I'm redoing database handling in the next version, but until then I guess I recommend using SQLite.

**Comment by Nentify** [comment]
ok thank you, i will try using sqlite

**Comment by madtomic** [comment]
Be nice if you can just use a command to return all unsold items in the market.

**Comment by Nentify** [comment]
Hasn't re-occured since switching to SQLite. Thanks!
