### ISSUE TITLE
Command to return all unsold items on market

### ISSUE THREAD

**Issue by madtomic** [Dasfaust/GlobalMarket#38]
Please consider to add a command to return all unsold items in the market.

**Comment by Dasfaust** [comment]
That is already a feature. /market cancelsearch all

**Comment by madtomic** [comment]
No, I meant admin command to return all listing on the market. Like a shut down or clean up command.

**Comment by Dasfaust** [comment]
It cancels all active listings and returns the items to the sellers' mailboxes. If you want a command to transfer all items to their inventories, that'd be hard to do if they are offline.

**Comment by madtomic** [comment]
I see. thank you
