### ISSUE TITLE
Problem with finally working Global Market

### ISSUE THREAD

**Issue by koalalord9999** [Dasfaust/GlobalMarket#39]
Alrighty, so after who knows how long of me trying, I just hit another brick wall.
http://prntscr.com/5rutv1

I've looked into configs but I dont see anything. :l
Do I have to set something up in Vault for it to take full functionality of the in game currency?

**Comment by Dasfaust** [comment]
Look for messages in your console. What economy plugin are you using?

**Comment by koalalord9999** [comment]
Essentials I believe.

[GlobalMarket] Error while building queued statement:
INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
13.01 16:57:36 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
13.01 16:57:36 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
13.01 16:57:36 [Server] INFO at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source) ~[?:?]
13.01 16:57:36 [Server] INFO at com.survivorserver.GlobalMarket.InterfaceListener.clickEvent(InterfaceListener.java:109) ~[?:?]
13.01 16:57:36 [Server] INFO at com.survivorserver.GlobalMarket.ListingsInterface.handleLeftClickAction(ListingsInterface.java:248) ~[?:?]
13.01 16:57:36 [Server] INFO at com.survivorserver.GlobalMarket.MarketCore.buyListing(MarketCore.java:78) ~[?:?]
13.01 16:57:36 [Server] INFO at com.survivorserver.GlobalMarket.MarketStorage.storePayment(MarketStorage.java:847) ~[?:?]
13.01 16:57:36 [Server] INFO at com.survivorserver.GlobalMarket.Market.getItemName(Market.java:575) ~[?:?]
13.01 16:57:36 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_7_R4.inventory.CraftItemStack cannot be cast to me.dasfaust.GlobalMarket.WrappedItemStack

**Comment by tr0nlegacy2012** [comment]
We are using craftconony 3

**Comment by koalalord9999** [comment]
OKAY sorry - the Currency plugin is Craftconomy3

**Comment by Dasfaust** [comment]
Sorry for the delay, should fixed in [build 10](http://build.survivorserver.com/job/GlobalMarket/10/).
