### ISSUE TITLE
other player's mailbox view

### ISSUE THREAD

**Issue by ashower** [Dasfaust/GlobalMarket#40]
is it possible to add a way to visualize other players mailbox with corresponding permission? something along lines of "/market mail [playername], with globalmarket.quickmail.others node - similar way to how essentials /invsee command works
it would be useful for moderator checks. 

i can describe the details onhere incase it's needed.

**Comment by Dasfaust** [comment]
This is already a feature. If you have globalmarket.admin, you can use /market mail <name> to view another player's mailbox.

**Comment by ashower** [comment]
Hi, thanks for that. What I was looking for was a separate node permission only for view the player mailbox without giving the moderator a full globalmarket.admin (that comes with config reloads, market purges etc.) - that's a too much big hammer.

**Comment by Dasfaust** [comment]
Sorry for the delay, I added 'globalmarket.quickmail.others' in [build 10](http://build.survivorserver.com/job/GlobalMarket/10/).

**Comment by ashower** [comment]
Thanks, I'll be testing it, meantime - is the curse donation option through paypal still valid? :-)

**Comment by ashower** [comment]
update: works as intended, many thanks :-)
