### ISSUE TITLE
Sometimes items aren't removed from market

### ISSUE THREAD

**Issue by Nentify** [Dasfaust/GlobalMarket#42]
I believe sometimes items aren't removed from the market after removal by the seller (not sure if it affects purchased). Clicking the item in the market produces the error:

```
[12:28:34 WARN]: [GlobalMarket] Null IMarketItem in InventoryClickEvent with position 5 (raw: 5) in interface Listings, should have an ID of 5864.
```

Last ender pearl in this screenshot (searched for seller's username):

http://i.nentify.me/Ee5rg2gN.png

**Comment by Dasfaust** [comment]
This should be fixed in [build 11](http://build.survivorserver.com/job/GlobalMarket/11/artifact/build/libs/GlobalMarket-1.3.0-11.jar).

**Comment by Nentify** [comment]
Seems fixed, thanks!
