### ISSUE TITLE
*Some* items not been saved to the database

### ISSUE THREAD

**Issue by externo6** [Dasfaust/GlobalMarket#48]
Some items, such as a blaze spawner is not been saved to our items table.
We use SQLLite instead on MySQL due to the transaction log issue.

At the moment we have a problem where players cannot sell blaze spawners, if you create a listing it will show it until the server restarts (or you reload the plugin) 
The plugin fails to save the item into the item table. 
http://gyazo.com/afb82f846ab8c54757004e75412cbec7
As you can see from that screenshot it is missing out ID's on where these items should be thus removing them from the market because they have not been saved.

If you want I can send you our database as creating a new one seems to solve this issue. But that is not an option really as we have already had to clear the database multiple times due to similar issues. I would rather help on getting them fixed.

**Comment by Dasfaust** [comment]
Upload a copy of your DB and I'll take a look. Are you using a plugin to allow spawner breaking/placing? Can I have a link so I can test?

**Comment by externo6** [comment]
I've sent you a bukkit message as the database contains player names etc 
We are using silkspawners located here: http://dev.bukkit.org/bukkit-plugins/silkspawners/

**Comment by Shybella** [comment]
Having this same issue.
