### ISSUE TITLE
Having trouble building with Gradle

### ISSUE THREAD

**Issue by chamunks** [Dasfaust/GlobalMarket#49]
http://ci.nixium.com/job/GlobalMarket/6/console
Would you be willing to share your settings for http://build.survivorserver.com/job/GlobalMarket/11/console

**Comment by Dasfaust** [comment]
I have the [Gradle Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Gradle+Plugin), and [here's my build task](http://puu.sh/g8hRg/eba7baa6db.png). That's about it.
