### ISSUE TITLE
Server becomes unresponsive.

### ISSUE THREAD

**Issue by Kainzo** [Dasfaust/GlobalMarket#55]
The server becomes unresponsive due to a player lookup or something similar.
git-Spigot-52df9dd-ab309d7 (MC: 1.8.3)
http://paste2.org/s6w2750U
https://www.irccloud.com/pastebin/ibVcSWQD

Removing the plugin removes this error.

**Comment by Dasfaust** [comment]
Which build are you using?

**Comment by Kainzo** [comment]
We were using latest Jenkins at the time, forked and removed the offline permission calls and that fixed it.

ZPermissions database kept stalling on this.

**Comment by Dasfaust** [comment]
I see, I will try to avoid it in 2.0.0. Thanks.
