### ISSUE TITLE
Exception in market command

### ISSUE THREAD

**Issue by AnodyneEntity** [Dasfaust/GlobalMarket#58]
Updated to GlobalMarket 2 because of the multi server support, get this error whenever trying to run /market.

---
http://pastebin.com/5hHDpymy

**Comment by Dasfaust** [comment]
You need ProtocolLib. If using 1.7.10, use [this version](http://ci.shadowvolt.com/job/ProtocolLib/lastSuccessfulBuild/com.comphenix.protocol$ProtocolLib-v1_7_R4/). For 1.8 and up, use [this](http://ci.shadowvolt.com/job/ProtocolLib/lastSuccessfulBuild/). I am going to add this information to the Jenkins build page but I can't figure out how to make a link as HTML isn't being parsed, haha.

**Comment by AnodyneEntity** [comment]
Will this work with KCauldron? I'm using the Cauldron supported version of ProtocolLib.

**Comment by Dasfaust** [comment]
Yes, the linked 1.7.10 build works with KCauldron (in my experience.) Is there a specific port for Cauldron/KCauldron?

**Comment by AnodyneEntity** [comment]
Oh, as well, did you get rid of MySQL support with GlobalMarket 2? Cause when I generate the configs, it doesn't show any login requires for MySQL.

**Comment by Dasfaust** [comment]
I did. I moved to flatfile JSON storage as the default option and [Redis](http://redis.io/) for multi-server support. So you'll need to have a Redis server running for that.

**Comment by AnodyneEntity** [comment]
Ah, gotcha, looks like I'll need to figure out how to setup Redis. Thank you.
