### ISSUE TITLE
Dupe Bug Reports

### ISSUE THREAD

**Issue by Nentify** [Dasfaust/GlobalMarket#59]
I've had reports of being able to duplicate items with the market for free.
> shift + space + right clicking on items in the market dupes them and aquires them without using any money.

and

> Space  + click   dupes a single item.   Shift + click flickers the item into your inventory momentarily, but the item poofs immediately after.

**Comment by Dasfaust** [comment]
I think removing InventoryTweaks from the server side will stop it temporarily. I'll be adding a workaround for it in the mean time.

**Comment by Nentify** [comment]
Thanks, I shall do that for now.

**Comment by damonmensch** [comment]
To be honest, inventory tweaks shouldn't be installed on your server in the first place. It's a client side mod and serves no purpose on the server itself.

Unlike some other client side mods, inventory tweaks doesn't have any configs that override the client's.

**Comment by Nentify** [comment]
Does it not sync actions with the server to prevent 'glitchiness'? Some users have reported some weird behaviours already. But it'll have to do for now.

On 12 Jul 2015 5:20 am, damonmensch <notifications@github.com> wrote:
To be honest, inventory tweaks shouldn't be installed on your server in the first place. It's a client side mod and serves no purpose on the server itself.

Unlike some other client side mods, inventory tweaks doesn't have any configs that override the client's.

---

**Comment by Dasfaust** [comment]
I think InventoryTweaks does serve a purpose on the server. But this should be fixed in build 13+. I haven't tested it myself yet, but it's the same workaround that's in the old version.

**Comment by Dasfaust** [comment]
Closing in relation to #62.
