### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by Nentify** [Dasfaust/GlobalMarket#62]
- Put max stock stack into the stock management page (eg. 320/320 diamonds)
- Take out 1 stack
- Put 1 item back in at so that total is 63 less than the max (eg. 257)
- Hold a stack and attempt to add a full stack on to the stock slot
- The market stock slot will restock but you will keep the stack on your cursor

**Comment by Nentify** [comment]
Video: http://i.nentify.me/4CEGN81R.mp4

**Comment by Dasfaust** [comment]
Interesting, thanks for the detailed report, I'll look into it ASAP.

**Comment by DarwinTrue** [comment]
What is stock management? I cant find it.

**Comment by Nentify** [comment]
It's in Global Market 2, click the chest at the bottom in the market GUI.

**Comment by DarwinTrue** [comment]
Global Market 2? Where is it?
I'm using GM 1.3.0-12 on my 1.8.8 spigot server. Is it safe? Works fine for me.

**Comment by Nentify** [comment]
If GM 1 is working fine for you, I'd probably just stick with that for now. GM 2 is still in development but can be found under the 2.0.X branch. More info here: https://github.com/Dasfaust/GlobalMarket/tree/2.0.X

**Comment by Dasfaust** [comment]
Sorry it took so long, should be fixed now.

**Comment by prozhong** [comment]
Should add this same line to 
https://github.com/Dasfaust/GlobalMarket/blob/2.0.X/src/main/java/me/dasfaust/gm/menus/Menus.java#L155
