### ISSUE TITLE
/market help isn't working on 2.0.0

### ISSUE THREAD

**Issue by ghost** [Dasfaust/GlobalMarket#63]
Hey there,

Everytime i use /market help it just shows me the same messages, i can't use any other commands. Should i use 1.3.0 instead? :/

Thanks,

Sikatsu

**Comment by Dasfaust** [comment]
Can you paste your server's startup log? Sounds like there's an exception somewhere.

**Comment by ShaneSik** [comment]
[09:35:47] [Server thread/INFO]: [GlobalMarket] Enabling GlobalMarket v2.0.0-13
[09:35:47] [Server thread/INFO]: [GlobalMarket] Blacklist has 2 entries
[09:35:47] [Server thread/INFO]: [GlobalMarket] Locale file loaded as 'en_US': locale/en_US.json

Full log: http://pastebin.com/R1nGgA3B

Everytime when i do /market help i don't recieve any commands from GlobalMarket.
So when i do /market help i recieve: http://prntscr.com/8gikkv and whatever i do after, even /? market always gives me the message from this picture. Means i'm unable to do anything or use any commands.

**Comment by Dasfaust** [comment]
It's working correctly, there just aren't any commands yet. Progress has been slow on version 2 and there's currently a dupe bug with the stock system, so I'd disable stock management in the config or stick with 1.3.0 for now. Sorry for the confusion! Going to keep this open until commands are finished.

**Comment by ShaneSik** [comment]
Thanks for your reply. It's one of the best market systems and i found out some populair dutch servers used it aswell. I also have another issue with snapshot 1.3.0. If you give me 10minutes i'll post it within another issue. I've made a world file about it. :)
