### ISSUE TITLE
Snapshot 1.3.0 issue

### ISSUE THREAD

**Issue by ghost** [Dasfaust/GlobalMarket#64]
This is feedback from my players using your plugin.

Dear,

We believe to have found a bug in your plugin GlobalMarket
In short: we experienced that the items created on the market are grouped together based on their price per piece. However, withdrawing one of the offers doesn't change the total amount of that item available on the market. Only buying one of those items, reset the total amount to the correct number.
In our example the command "/market create price amount" is used in several ways
First the command was used 14 times to sell 14 diamonds. "/market create 3000 1"
Next the command was used 12 times to sell 12 diamonds. "/market create 2000 1"
--> Thus the players are able to buy diamonds one at the time.
Now the command was used 1 time to sell 30 diamonds. "/market create 60000 30"
--> Instead of creating a third stack of diamonds on the market. These 30 diamonds were added to the stack of 12. Hovering over the stack displayed: "1 of the 42".
Now the seller withdrew his last offer, retrieving 30 diamonds. Ingame still shows: "1 of the 42".
Afterwards, the command was used one more time to sell 12 diamonds. "/market create 24000 12"
--> Again these diamonds were added to the same stack. Hovering over the stack of diamonds displayed: "1 of the 54"
Finally another player bought 1 diamond (from our previous mentioned stack). Only now the correct total amount is shown: "12 of the 23".

Conclusion: A wrong number of the total amount is shown when offers are withdrawn. The value only gets updated when one of the items is bought.
It's also weird that now the last offer of 12 diamonds is placed before the 11 remaining offers. (Forcing the other players to buy 12 diamonds at once, instead of one at the time).

**Comment by Dasfaust** [comment]
So it's just a visual bug? The listing 'stacking' was a complete afterthought and has a few weird behaviors in certain situations. [Version 2](https://github.com/Dasfaust/GlobalMarket/tree/2.0.X#version-200-beta) has a much better system for keeping spam at bay called stock. If it's too annoying, I'd go ahead and switch to version 2. I've recently fixed a few bugs and it should be stable enough for production use.

**Comment by Sikatsu** [comment]
It seems to be a visual issue yes. As for version 2 i've tried that system but it seems we are unable to open the mailbox, assign it to a chest ect because there are no commands yet.
