### ISSUE TITLE
Cant run the sudo command to autopopulate market in v2.0+ 

### ISSUE THREAD

**Issue by DraksterAU** [Dasfaust/GlobalMarket#70]
Hi Dausfast,

Since v2.0 I am unable to autoload our market with outside scripts that run the sudo command on my ingame player from the console.

Is it possible you can look at this?

Previously running this from console would work:

- sudo give {player} 131 1
- sudo {player} market createinf 100 1 

Now it just comes up with the listings menu ingame.. I think it m ight be to do with your wildcard to pick up on listings, mailbox etc.

REALLY appreciate if this could be resolved as 1.3 to 2.0 wiped our market of 10,000 items and I had to downgrade :(

**Comment by Dasfaust** [comment]
I know this is a 3-month old issue, it should finally be resolved, as long as the player has permission. I tested with [this plugin](http://dev.bukkit.org/bukkit-plugins/sudo/), seems to be working.

**Comment by DraksterAU** [comment]
@Dasfaust You rock man. You bloody rock!
Looking forward to using the awesome version of GlobalMarket :D

**Comment by DraksterAU** [comment]
PS : Essentials has Sudo too :)
