### ISSUE TITLE
Just a BUG of lost items

### ISSUE THREAD

**Issue by D-lingr** [Dasfaust/GlobalMarket#72]
Hey guy,good evening.
At first,happy new year!I am a Chinese boy,so I can't speak English very well.This is my first time to talk in this forum.
This is the BUG picture.【http://i4.tietuku.com/b829d72cc00b3abb.jpg】
If you put item up in this GUI，the items lose.
This is BUG.
This is translation of chinese
新年快乐！这是我第一次在这个论坛说话，所以有点紧张
BUG就是当你把物品放进GUI界面后会丢失他们
这就是那个BUG

**Comment by xyblues** [comment]
![r ocf79k1n 0 2hlj51cj0](https://cloud.githubusercontent.com/assets/15712089/12074634/4264d8f8-b199-11e5-9402-4f94a8ba70ed.jpg)

**Comment by MineTheCube** [comment]
This bug is still here is last version, we can easily but items in this menu, and they are all lost when the menu is closed.
