### ISSUE TITLE
Not remove listing if player buy. And not send money to player sell!

### ISSUE THREAD

**Issue by vanthoi** [Dasfaust/GlobalMarket#79]
This server is running CraftBukkit version git-Spigot-1649 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT

It is not remove listing and not add money on player sell!

please fix Thanks!

**Comment by Dasfaust** [comment]
Need plugin version, economy plugin you're using, its version, Vault version, and server logs. Otherwise I can't be of much help. Things are working fine on my test setup.

**Comment by vanthoi** [comment]
version 2.0.21  http://build.survivorserver.com/job/GlobalMarket%202.0.0/21/
potocolib http://ci.shadowvolt.com/job/ProtocolLib/178/com.comphenix.protocol$ProtocolLib-v1_7_R4/
essential & fe plugin good on bukkit but not work on spigot 1.7.10 for client 1.7.x to 1.8.x
vault new.
