### ISSUE TITLE
createserverlisting

### ISSUE THREAD

**Issue by freakyy85** [Dasfaust/GlobalMarket#84]
Createserverlisting is bugged. it tells me: invalid amount specified for input string serverlisting.
i use it like /market createserverlisting 500 1

**Comment by DraksterAU** [comment]
Might need to use /market createinf x x or market create x x -inf?

**Comment by DraksterAU** [comment]
https://github.com/Dasfaust/GlobalMarket/commit/87c4e2e264fa0fa7e1517665f6a4a31022ee3b8b

**Comment by freakyy85** [comment]
i used that but it doesnt work. as i said i tried like always, /market createinf 500 1 
but it says: invalid amount specified - the only thing i didnt try was market create x x -inf.

**Comment by DraksterAU** [comment]
@freakyy85 I'm updating my server at present. Will test it out.

**Comment by DraksterAU** [comment]
@Dasfaust Looks like the wildcard functionality in your commands is at it again.. this time "createinf" is being flagged as "create" and not using the server listing command.

Quick n dirty way around this is to make the command "infcreate" and "inflist" I think...

**Comment by Dasfaust** [comment]
Now fixed in build 30+.
