### ISSUE TITLE
Update Libs with actual dependencies and/or link to them

### ISSUE THREAD

**Issue by StargateMC** [Dasfaust/GlobalMarket#87]
Can you please link in Your dependencies to the libs folder on GitHub?

Would love to help out if I can .... but Not sure what libraries relating to redis your using.

**Comment by Dasfaust** [comment]
Late reply (I know, I know) but it should all be available from the maven repos listed in the buildscript. Are you getting an error? The actual redis library can be downloaded [here](https://github.com/Dasfaust/johm/blob/mvn-repo/redis/johm/0.6.3/johm-0.6.3.jar).
