### ISSUE TITLE
[GM2] Items become unlisted after being purchased

### ISSUE THREAD

**Issue by Time6628** [Dasfaust/GlobalMarket#91]
How to reproduce:
1. List an item on the market with more than 1 stock.
2. Have a player buy that item.
3. The item will become removed from the listings and the seller will have to relist the item onto the market, the item will always become removed _even_ if there is still stock available.

**Comment by Pigna** [comment]
I can verify this.

**Comment by Dasfaust** [comment]
Should be fixed in build 30, please re-open the issue if it's no the case.
