### ISSUE TITLE
Some bugs in 29 build

### ISSUE THREAD

**Issue by Bodyash** [Dasfaust/GlobalMarket#92]
If u force put some items in empty slot - and close market windows - u will lose item.
![default](https://cloud.githubusercontent.com/assets/2454569/14660260/82b31196-06ac-11e6-8a35-95bfaca95334.PNG)
Blacklist doest work?
![2](https://cloud.githubusercontent.com/assets/2454569/14660261/82b6a5b8-06ac-11e6-9dd3-b95350ea096e.PNG)
![3](https://cloud.githubusercontent.com/assets/2454569/14660262/82b73a14-06ac-11e6-8f3e-90bea2276ba4.PNG)

**Comment by Dasfaust** [comment]
For losing items in empty slots, the easy fix is just to not put items in empty inventory slots, and inform your players to do the same. I doubt I can fix it as the events are already cancelled and it seems to be a Bukkit issue.

Blacklisting should be fixed in build 31.
