### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by NoHoPeLess** [Dasfaust/GlobalMarket#93]
Oh first time i add an feature request...hope im right here...

Please add:

-An history for players when they are offline
-normal mysql support, our network dont use redis
-an message shown up when someone buy from an user (for the two users, example: User NAME bought 64 Cobble from you > You have bought 64 cobble from User NAME

This is very important for our network, when u like i can buy u an coffee for this?

Greetz

**Comment by Dasfaust** [comment]
1: History is a planned feature! No ETA though. The biggest thing holding history back is you can't access human-readable item names from the server side, so I'll have to figure that out and support multiple languages, and modded items if at all possible.
2: I won't be doing MySQL in version 2.X, read more [here](https://github.com/Dasfaust/GlobalMarket/issues/94). It's just not feasible to use MySQL for any cross-server interaction. Redis support is also kind of buggy and needs work.
3: Will come with history once item names are sorted out.

**Comment by NoHoPeLess** [comment]
Ok thank you so much! :D
