### ISSUE TITLE
Request: Console command to force open market interface 

### ISSUE THREAD

**Issue by DraksterAU** [Dasfaust/GlobalMarket#95]
Hi Dasfaust,

Hoping you can help.

I'm after a console command to force open a market interface for the specified player if they are online.

And an ability to disable the actual market command (permissions is fine if you want to do it that way).

Reason is so I can have my npcs calling the market interface and disallow players not need a market NPC access to the market.

This could be done with a combination of plugins to restrict commands to a specific area - but that is really complex.

I used to just place a chest under the NPC and make it so the command could only be used within 10 blocks of it, but it looks like you've removed that in 2.0.

Hope you can help.

Regards
DraksterAU

**Comment by Dasfaust** [comment]
Ok, done! I added a config option to disable /market going directly to the GUI. There's now `/market browse` with console support. Usages:
`/market browse` opens the GUI
`/market browse stock` opens the Stock GUI
`/market browse <player>` opens the GUI for a player
`/market browse stock <player>` opens the Stock GUI for a player

**Comment by DraksterAU** [comment]
Thanks :D 
This works wonders.
